import React, { useState } from 'react';
import { ArrowLeft, Plus, ChevronDown, ChevronUp } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'motion/react';
import { toast } from 'sonner';
import { storageService } from '../services/storageService';
import { FicheData } from '../utils/documentTemplate';
import { useAuth } from '../context/AuthContext';

export default function ManualForm() {
  const navigate = useNavigate();
  const { profile, refreshProfile } = useAuth();
  const [openSection, setOpenSection] = useState<string | null>('header');
  const [templateType, setTemplateType] = useState('classic');
  const [formData, setFormData] = useState({
    subject: '',
    theme: '',
    class: '',
    date: new Date().toISOString().split('T')[0]
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  const toggleSection = (section: string) => {
    setOpenSection(openSection === section ? null : section);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async () => {
    if (!formData.theme || !formData.subject) {
      toast.error('Veuillez remplir au moins le thème et la matière.');
      return;
    }

    // Restriction Plan Gratuit
    if (profile?.tier === 'free' && profile.lessons_count >= 3) {
      toast.error("Limite atteinte", {
        description: "Vous avez atteint la limite de 3 fiches pour le plan Gratuit (Populaire). Passez au plan Pro pour continuer !",
        action: {
          label: "Voir les tarifs",
          onClick: () => navigate('/pricing')
        }
      });
      return;
    }

    setIsSubmitting(true);
    try {
      const newFiche: FicheData = {
        id: '', // Will be generated by DB
        titre: formData.theme,
        numeroFiche: '',
        enTete: {
          matiere: formData.subject,
          theme: formData.theme,
          objectifGeneral: '',
          classe: formData.class,
          temps: '1H',
          date: formData.date
        },
        miseEnSituation: {
          rappel: '',
          prerequis: '',
          motivation: ''
        },
        sequences: [
          { id: '1', numero: '1', objectif: '', taches: '', organisations: '', savoirs: '', materiel: '', duree: '' }
        ],
        syntheseLecon: '',
        evaluationFormative: '',
        documentEleve: {
          activite: '',
          objectifGeneral: '',
          consigne: '',
          texte: '',
          support: '',
          taches: '',
          strategie: { travailGroupe: '', pleniere: '' }
        },
        ficheSynthese: {
          point1: '',
          point2: '',
          point3: ''
        }
      };

      const savedId = await storageService.saveFiche(newFiche);
      toast.success('Fiche créée avec succès !');
      await refreshProfile(); // Refresh usage stats
      navigate(`/dashboard/editor/${savedId}`);
    } catch (error) {
       console.error(error);
       toast.error('Erreur lors de la création de la fiche');
    } finally {
       setIsSubmitting(false);
    }
  };

  const handleDraft = () => {
    toast.success('Brouillon enregistré (localement pour l\'instant)');
  };

  const handleComingSoon = (e: React.MouseEvent) => {
    e.preventDefault();
    toast.info('Bientôt disponible', {
      description: 'Cette fonctionnalité est en cours de développement.'
    });
  };

  const getSectionTitles = () => {
    switch (templateType) {
      case 'tp':
        return {
          situation: 'Problématique & Hypothèses',
          sequences: 'Protocole Expérimental',
          synthesis: 'Analyse des Résultats'
        };
      case 'literature':
        return {
          situation: 'Contexte & Auteur',
          sequences: 'Axes de Lecture',
          synthesis: 'Bilan & Ouverture'
        };
      case 'revision':
        return {
          situation: 'Notions Clés',
          sequences: 'Points Essentiels',
          synthesis: 'Quiz Rapide'
        };
      default:
        return {
          situation: 'Mise en situation',
          sequences: 'Séquences pédagogiques',
          synthesis: 'Synthèse & Évaluation'
        };
    }
  };

  const titles = getSectionTitles();

  return (
    <div className="max-w-7xl mx-auto py-6 md:py-8 flex flex-col lg:flex-row gap-8 h-full">
      
      {/* Left Column - Form (70%) */}
      <div className="w-full lg:w-[65%] xl:w-[70%] flex flex-col h-full">
        <div className="mb-6 flex justify-between items-center">
          <Link to="/dashboard/create" className="inline-flex items-center gap-2 text-sm text-edu-dark hover:text-edu-black transition-colors">
            <ArrowLeft size={16} /> Retour aux options
          </Link>
          
          <div className="flex items-center gap-3">
            <label className="text-xs font-medium text-edu-dark uppercase tracking-wider">Modèle :</label>
            <select 
              value={templateType}
              onChange={(e) => setTemplateType(e.target.value)}
              className="px-3 py-1.5 bg-white border border-edu-light/50 rounded-[2px] outline-none focus:border-edu-red text-sm font-serif text-edu-black cursor-pointer"
            >
              <option value="classic">Séquence de cours classique</option>
              <option value="tp">Travaux Pratiques / Sciences</option>
              <option value="literature">Analyse Littéraire / Langues</option>
              <option value="revision">Fiche de Révision</option>
            </select>
          </div>
        </div>

        <h2 className="font-serif text-3xl text-edu-black mb-8">Créez votre fiche pas à pas</h2>

        <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-4 pb-20">
          
          {/* Card 1 - En-tête */}
          <div className="bg-white border border-edu-light/50 rounded-[2px] shadow-sm overflow-hidden">
            <button 
              onClick={() => toggleSection('header')}
              className="w-full px-6 py-4 flex justify-between items-center bg-[#F5F2ED]/50 hover:bg-[#F5F2ED] transition-colors"
            >
              <h3 className="font-serif text-lg font-bold text-edu-black">En-tête de la fiche</h3>
              {openSection === 'header' ? <ChevronUp size={20} className="text-edu-dark" /> : <ChevronDown size={20} className="text-edu-dark" />}
            </button>
            <AnimatePresence>
              {openSection === 'header' && (
                <motion.div 
                   initial={{ height: 0, opacity: 0 }}
                   animate={{ height: 'auto', opacity: 1 }}
                   exit={{ height: 0, opacity: 0 }}
                   className="px-6 py-5 border-t border-edu-light/30"
                >
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    <div className="flex flex-col gap-1">
                      <label className="text-xs font-medium text-edu-black">Matière</label>
                      <input type="text" name="subject" value={formData.subject} onChange={handleInputChange} className="w-full px-3 py-2 bg-white border border-edu-light/50 rounded-[2px] outline-none focus:border-edu-red text-sm" placeholder="Ex: Français, Mathématiques, MEL" />
                    </div>
                    <div className="flex flex-col gap-1">
                      <label className="text-xs font-medium text-edu-black">Classe</label>
                      <input type="text" name="class" value={formData.class} onChange={handleInputChange} className="w-full px-3 py-2 bg-white border border-edu-light/50 rounded-[2px] outline-none focus:border-edu-red text-sm" placeholder="Ex: 2nde, Terminale, BTS" />
                    </div>
                    <div className="flex flex-col gap-1 md:col-span-2">
                      <label className="text-xs font-medium text-edu-black">Thème principal</label>
                      <input type="text" name="theme" value={formData.theme} onChange={handleInputChange} className="w-full px-3 py-2 bg-white border border-edu-light/50 rounded-[2px] outline-none focus:border-edu-red text-sm" />
                    </div>
                    <div className="flex flex-col gap-1">
                      <label className="text-xs font-medium text-edu-black">Date</label>
                      <input type="date" name="date" value={formData.date} onChange={handleInputChange} className="w-full px-3 py-2 bg-white border border-edu-light/50 rounded-[2px] outline-none focus:border-edu-red text-sm" />
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="bg-white border border-edu-light/50 rounded-[2px] shadow-sm p-6 text-center italic text-edu-dark">
            Remplissez l'en-tête pour commencer, puis finalisez dans l'éditeur complet.
          </div>

        </div>

        {/* Global Buttons */}
        <div className="mt-auto pt-6 border-t border-edu-light/30 flex justify-end items-center bg-edu-bg z-10">
          <button 
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="px-8 py-2.5 bg-edu-red text-white rounded-[2px] hover:bg-[#5a0808] transition-all shadow-[0_4px_14px_rgba(126,11,11,0.3)] font-medium text-sm disabled:opacity-50"
          >
            {isSubmitting ? 'Création en cours...' : 'Créer et continuer dans l\'éditeur'}
          </button>
        </div>
      </div>

      {/* Right Column - Live Preview */}
      <div className="hidden lg:flex lg:w-[35%] xl:w-[30%] flex-col h-full sticky top-0">
        <h3 className="font-serif text-xl text-edu-black mb-6">Aperçu rapide</h3>
        <div className="bg-white border border-edu-light shadow-xl rounded-[2px] p-6 flex flex-col items-center justify-start overflow-hidden relative aspect-[1/1.414]">
           <div className="w-full h-full bg-[#F5F2ED] border border-edu-light/50 p-4">
              <div className="border-b border-edu-black pb-2 mb-4">
                 <div className="font-serif text-lg font-bold">{formData.theme || "Nouveau projet"}</div>
                 <div className="text-xs text-edu-dark">{formData.subject} - {formData.class}</div>
              </div>
              <div className="space-y-4">
                 <div className="h-2 w-3/4 bg-edu-light/30 rounded"></div>
                 <div className="h-2 w-full bg-edu-light/30 rounded"></div>
                 <div className="h-2 w-1/2 bg-edu-light/30 rounded"></div>
              </div>
           </div>
        </div>
      </div>

    </div>
  );
}
